export enum ErrorCode {
	AUTH_USER_DISABLED = 'AUTH_USER_DISABLED',
	AUTH_INVALID_DETAILS = 'AUTH_INVALID_DETAILS',
	AUTH_WEAK_PASSWORD = 'WEAK_PASSWORD',
	AUTH_REAUTH_REQUIRED = 'AUTH_REAUTH_REQUIRED',
	AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
	AUTH_INVALID_ACTION_CODE = 'AUTH_INVALID_ACTION_CODE',
	UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}